### ISSUE TITLE
Allow EDT to ignore attribute level balance

### ISSUE THREAD

**Issue by ighdez** [ighdez/EDT#1]
By default, EDT gives an error if we use a NSC that is not a multiple of the number of levels. Cannot ignore attribute level balance.

Goal: allow to ignore attribute level balance (with a warning)

**Comment by stellamulia** [comment]
Hi Ignacio, I have a suggestion for [edt_functions.py](https://github.com/ighdez/EDT/blob/master/edt_functions.py) line **399** such that the attribute levels do not have to appear the same number of times, but still as balanced as possible:
`dd = np.array((ATTLIST[k]['levels'] * int(np.ceil(NRUNS/LEVS[k])))[:NRUNS])`
`dd.sort()`

Do you think this is a suitable workaround? Thanks!

**Comment by ighdez** [comment]
Hey @stellamulia , sorry for dropping on this so late. I checked the suggestion and it works until the generation of blocks (line **273** of `edt_functions.py`). I'm working on it.

**Comment by stellamulia** [comment]
Thank you for checking and incorporating the suggestion! 👍
