### ISSUE TITLE
Design cannot be generated when opt-out option is not present

### ISSUE THREAD

**Issue by stellamulia** [ighdez/EDT#3]
For example, changing the option 'optout' from 1 to 0 in [example.py](https://github.com/ighdez/EDT/blob/master/example.py) throws an error `cannot reshape array of size 118 into shape (120,1)`

**Comment by ighdez** [comment]
Interesting @stellamulia ...checking on it...

**Comment by ighdez** [comment]
Now I realised what happened @stellamulia:  in line **116** of `edt_functions.py` it should be:

`grprow = np.repeat(np.arange(1,NCS+1),NALT)`

If you see, the array created with `np.arange` should be from 1 to `NCS+1`. Otherwise, it ignores the last row.

**Comment by stellamulia** [comment]
Awesome! Thank you @ighdez 👍
